name: Test Schedule

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Test Schedule Job
        run: echo "This job was automatically run!"
