name: Scheduled Workflow

on:
  schedule:
    - cron: "*/10 * * * *"
    
jobs:
  Explore-Timed-GitHub-Actions:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "This job was automatically run!"
